name: Hugo site CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Init git
      run: |
        git config --global user.name "Xcalizorz"
        git config --global user.email "Xcalizorz@users.noreply.github.com"
    - name: Build the site in my hugo container (zrezai-dev.de)
      run: |
        docker run \
        -v ${{ github.workspace }}/dev:/tmp \
        xcalizorz/hugo:1.0-alpine /bin/bash -c "hugo --minify --baseUrl https://zrezai-dev.de/ --destination html/public"

        git commit -am "auto(zrezai-dev.de): CI Update"
    - name: Build the site in my hugo container (server.zrezai-dev.de)
      run: |
        docker run \
        -v ${{ github.workspace }}/dev:/tmp \
        xcalizorz/hugo:1.0-alpine /bin/bash -c "hugo --minify --baseUrl https://server.zrezai-dev.de/ --destination html/server"

        git commit -am "auto(server.zrezai-dev.de): CI Update"
    - name: Push changes
      run: |
        git push

