version: "3.8"

services:
  blog_builder:
    image: klakegg/hugo:latest
    deploy:
      replicas: 1
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: none
      labels:
        - traefik.enable=false
    volumes:
      - ./dev:/src
    networks:
      - web

  blog:
    image: nginx:alpine
    deploy:
      replicas: 2
      placement:
        max_replicas_per_node: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 30s
      labels:
        - com.centurylinklabs.watchtower.enable=true
        - traefik.enable=true
        - traefik.http.routers.blog.service=blogService
        - traefik.http.routers.blog.tls=true
        - traefik.http.routers.blog.tls.certresolver=zrezaiResolver
        - traefik.http.routers.blog.entrypoints=websecure
        - traefik.docker.network=web
        - traefik.http.services.blogService.loadbalancer.server.port=80
        - traefik.http.services.blogService.loadbalancer.passhostheader=true
        - traefik.http.services.blogService.loadbalancer.sticky.cookie=true
        - traefik.http.routers.blog.rule=Host(`server.zrezai-dev.de`)
        - "traefik.http.routers.blog.middlewares=blogHeaders@file"
    depends_on:
      - blog_builder
    volumes:
      - ./dev/public:/usr/share/nginx/html
    networks:
      - web

networks:
  web:
    driver: overlay
    name: web
    driver_opts:
      encrypted: "true"
