version: "3.8"

services:
  blog_builder:
    image: xcalizorz/hugo:1.0-alpine
    volumes:
      - ./dev:/tmp
    command: hugo --minify --baseUrl https://zrezai-dev.de/ --destination html/server

  blog:
    image: nginx:alpine
    depends_on:
      - blog_builder
    volumes:
      - ./dev/html/server:/usr/share/nginx/html
