DefaultContentLanguage = "de"
languageCode = "de-de"
title = "Zadjad Rezai."
theme = "PaperMod"
enableEmoji = true

[outputs]
  home = ['html', 'amp', 'rss']

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "emacs"
    tabWidth = 2
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[imaging]
  # Default resample filter used for resizing. Default is Box,
  # a simple and fast averaging filter appropriate for downscaling.
  # See https://github.com/disintegration/imaging
  resampleFilter = "box"

  # Default JPEG quality setting. Default is 75.
  quality = 75

  # Anchor used when cropping pictures.
  # Default is "smart" which does Smart Cropping, using https://github.com/muesli/smartcrop
  # Smart Cropping is content aware and tries to find the best crop for each image.
  # Valid values are Smart, Center, TopLeft, Top, TopRight, Left, Right, BottomLeft, Bottom, BottomRight
  anchor = "smart"

  # Default background color.
  # Hugo will preserve transparency for target formats that supports it,
  # but will fall back to this color for JPEG.
  # Expects a standard HEX color string with 3 or 6 digits.
  # See https://www.google.com/search?q=color+picker
  bgColor = "#ffffff"

[params]
  subtitle = "DevOps."
  DateForm = "02.01.2006"
  enableReadingTime=true
  favicon = "/img/favicon/favicon.ico"
  mainvideo = "https://i.giphy.com/media/7GHRDluBmx9O8/giphy.webp"
  description = "Ich bin ein DevOps Enginner mit Liebe zum Detail und komplexen Aufgaben. In meinem Blog schreibe ich über verschiedene Dinge aus dem IT-Umfeld."
  ShowReadingTime = true

  [params.homeInfoParams]
  Title = "Site Reliability Engineer"
  Content = "🚀"

  [[params.socialIcons]]
  name = "Github"
  url = "github.com/zadjadr"

  [[params.socialIcons]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/zadjad-rezai"



[taxonomies]
  tag = "tags"
  category = "categories"


[[menu.main]]
  url = "/index.html"
  name = "Home"
  weight = 1

[[menu.main]]
  url = "/categories"
  name = "Kategorien"
  weight = 2

[[menu.main]]
  url = "/posts"
  name = "Archiv"
  weight = 3

[[menu.main]]
  url = "/index.xml"
  name = "RSS Feed"
  weight = 4

[[menu.main]]
  url = "/datenschutz"
  name = "Datenschutz"
  weight = 5

[[menu.main]]
  url = "/impressum"
  name = "Impressum"
  weight = 6

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = true

[deployment]
  # By default, files are uploaded in an arbitrary order.
  # Files that match the regular expressions in the "Order" list
  # will be uploaded first, in the listed order.
  order = [".jpg$", ".webp$", ".gif$"]

[[deployment.matchers]]
  #  Cache static assets for 1 year.
  pattern = "^.+\\.(js|css|svg|ttf)$"
  cacheControl = "max-age=31536000, no-transform, public"
  gzip = true

[[deployment.matchers]]
  pattern = "^.+\\.(png|jpg|webm|webp|gif)$"
  cacheControl = "max-age=31536000, no-transform, public"
  gzip = false

[[deployment.matchers]]
  pattern = "^.+\\.(html|xml|json)$"
  gzip = true

[module]
[[module.mounts]]
  source = 'content'
  target = 'content'
[[module.mounts]]
  source = 'static'
  target = 'static'
[[module.mounts]]
  source = 'layouts'
  target = 'layouts'
[[module.mounts]]
  source = 'data'
  target = 'data'
[[module.mounts]]
  source = 'assets'
  target = 'assets'
[[module.mounts]]
  source = 'i18n'
  target = 'i18n'
[[module.mounts]]
  source = 'archetypes'
  target = 'archetypes'
