name: Trigger auto deployment for container-app-mfgxavwoywcqs

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-mfgxavwoywcqs-AutoDeployTrigger-51dcaf1d-f714-4f5a-92c6-e52026f7cb4f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPMFGXAVWOYWCQS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPMFGXAVWOYWCQS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPMFGXAVWOYWCQS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrymfgxavwoywcqs.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPMFGXAVWOYWCQS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPMFGXAVWOYWCQS_REGISTRY_PASSWORD }}
          containerAppName: container-app-mfgxavwoywcqs
          resourceGroup: zrezaidev8a7b
          imageToBuild: containerregistrymfgxavwoywcqs.azurecr.io/container-app-mfgxavwoywcqs:${{ github.sha }}
          


