name: Trigger auto deployment for container-app-z52mkns355k6u

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-z52mkns355k6u-AutoDeployTrigger-64a0cd5d-a193-48e7-a189-b39397eb522c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPZ52MKNS355K6U_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPZ52MKNS355K6U_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPZ52MKNS355K6U_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistryz52mkns355k6u.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPZ52MKNS355K6U_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPZ52MKNS355K6U_REGISTRY_PASSWORD }}
          containerAppName: container-app-z52mkns355k6u
          resourceGroup: zrezaidevb841
          imageToBuild: containerregistryz52mkns355k6u.azurecr.io/container-app-z52mkns355k6u:${{ github.sha }}
          


