name: Trigger auto deployment for container-app-djpzrcsfve7uq

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/container-app-djpzrcsfve7uq-AutoDeployTrigger-94a750f9-26b3-42b8-86c6-7922404a5316.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPDJPZRCSFVE7UQ_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPDJPZRCSFVE7UQ_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPDJPZRCSFVE7UQ_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: containerregistrydjpzrcsfve7uq.azurecr.io
          registryUsername: ${{ secrets.CONTAINERAPPDJPZRCSFVE7UQ_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPDJPZRCSFVE7UQ_REGISTRY_PASSWORD }}
          containerAppName: container-app-djpzrcsfve7uq
          resourceGroup: zrezaidev8d77
          imageToBuild: containerregistrydjpzrcsfve7uq.azurecr.io/container-app-djpzrcsfve7uq:${{ github.sha }}
          


