name: Hugo site CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    - name: checkout submodules
      run: |
        git config --file .gitmodules --get-regexp url | while read url; do
          git config --file=.gitmodules $(echo "$url" | sed -E "s/git@github.com:|https:\/\/github.com\//https:\/\/${{ secrets.CI_PAT }}:${{ secrets.CI_PAT }}@github.com\//")
        done
        git submodule sync
        git submodule update --init --recursive
    - name: Build the site in my hugo container (zrezai-dev.de)
      run: |
        docker run \
        -v ${{ github.workspace }}/dev:/tmp \
        xcalizorz/hugo:1.0-alpine /bin/sh -c "hugo --minify --baseUrl https://zrezai-dev.de/ --destination html/public"

        tar -zcvf ${{ github.workspace }}/public.tar.gz -C ${{ github.workspace }}/dev/html/public .
    - name: 'Upload zrezai-dev.de Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: public-html
        path: ${{ github.workspace }}/public.tar.gz
        retention-days: 3
    - name: Build the site in my hugo container (server.zrezai-dev.de)
      run: |
        docker run \
        -v ${{ github.workspace }}/dev:/tmp \
        xcalizorz/hugo:1.0-alpine /bin/sh -c "hugo --minify --baseUrl https://server.zrezai-dev.de/ --destination html/server"

        tar -zcvf ${{ github.workspace }}/server.tar.gz -C ${{ github.workspace }}/dev/html/server .
    - name: 'Upload server.zrezai-dev.de Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: server-html
        path: ${{ github.workspace }}/server.tar.gz
        retention-days: 3
